### ISSUE TITLE
Only controlls are left/right arrow keys

### ISSUE THREAD

**Issue by Michiocre** [TheKatze/o.o#1]
Would it be possible to enable walking using the a/d keys on the keyboard.
This has become the standard in most games.
See https://www.pcgamer.com/how-wasd-became-the-standard-pc-control-scheme/

**Comment by TheKatze** [comment]
First of all: thank you for your invaluable feedback. Messages like this help us shape our product to the needs of our community.

I have added this feature request to our backlog, though I am sorry to inform you that the priority is not very high.
However, if you do want to see this feature in the game earlier, feel free to tackle the issue yourself.

**Comment by thekatze** [comment]
Good news @Michiocre, we just merged the documentation onto master! 😄

**Comment by Michiocre** [comment]
closed in #4
